apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helmbasic-develop
  namespace: develop
spec:
  releaseName: helmbasic-develop
  chart:
    git: git@github.com:mifonpe/helmflux
    path: /
    ref: develop
  values:
    replicaCount: 1
    ingress:
      host: mywebserver.dev.kubesandclouds.com
